unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

set viminfo+=n~/.vim/viminfo " Store viminfo in .vim directory
set encoding=utf-8 " Use unicode

" Colours
if filereadable(expand("~/.vim/vimrc_background"))
  let base16colorspace=256
  source ~/.vim/vimrc_background
endif

set background=dark
syntax enable

" Indentation
set tabstop=4 " Visual tab size
set softtabstop=4 " How many spaces are inserted
set shiftwidth=4
set expandtab " Turns tabs into spaces
filetype plugin indent on

" UI and such
set ruler
set number
set wildmenu " visual autocomplete menu
set showmatch
set lazyredraw " not so sure about this one
set mouse=a
set splitright


" Line Wrapping
set wrap

" Searching
set incsearch " search as typing search expression

